name: gs-grid-ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      
      - name: Install & Build
        run: |
          yarn clean
          yarn install
          yarn build
