jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Install & Build
        run: |
          yarn clean
          yarn install
          yarn build
